import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { Literata } from 'next/font/google';

// Configure the font
const literata = Literata({
  subsets: ['latin'],
  weight: ['400', '700'], // Choose the weights you want
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
        <body className={literata.className}>
        {children}
      </body>
    </html>
  );
}
